---
title: "Common commands"
editor: source
tbl-cap-location: top
---

```{r, echo = FALSE}
source("./R/init.R")
log_info("Called common-commands notebook")
```


| Command  | Description of common use  |
|--------|--------|
| `git init`        | Create a new git repository.   |
| `git init --bare` | Create a new bare (no working directory) git repository for deployement as a remote on a fileserver.   |
| `git init --template = <dir>` | Create a repository from a specified template.   |
| `git clone <https://name-repos.git>` | Clone a remote by https (typically used via GitHub).  |
| `git add <name1> <name2>`  | Add one or more files.   |
| `git reset --hard <SOME-COMMIT>`  | V. dangerous. Know what you are doing. Reverse your branch back to the commit point.  |
| `git status`  | Retrieve the status of a repo, whether there are things to commit, untracked etc.   |
| `git diff`  | Difference between HEAD and current state of working dir   |
| `git diff HEAD~1` | Difference between HEAD and previous commit |
| `git diff <name>` | As above for a specific file.   |
| `git diff <bname1> <bname2> <name>` | As above for a specific file but between two branches.   |
| `git log --oneline --graph --decorate --all` | Give me full history    |
| `git commit -m "message"` | Create a new commit in the repository (tracking any untracked files) with reason for commit.   |
| `git branch <bname>` | Create a new branch, a divergence from the main development branch.   |
| `git push -u <remote> <bname>` | Push a local branch (commits) up to a remote repo. Remote is e.g. origin.   |
| `git push <remote> <bname>` | Push a local branch (commits) up to a remote repo.    |
| `git branch -d <bname>` | Delete a local branch being careful.    |
| `git fetch`  | Fetches the most recent state of repo, leaves working directory files alone.    |
| `git fetch <remote>` | Fetches from a specified remote, e.g. upstream |  
| `git fetch <remote/bname>` | Fetches from a specified remote and branch, e.g. upstream/main | 
| `git merge <bname>` | Merges changes into working dir for current branch.    |
| `git pull`  | Combines fetch and pull into one operation.   |
| `git revert <12345677>` | Reverts back to a commit point maintaining full history (safe).   |
| `git checkout <bname>` | Switch to a branch.    |
| `git checkout -b <bname>` | Shortcut to create and then switch to a branch.    |
| `git remote -v` | List the remotes that the local repo is currently aware of. |
| `git remote add upstream <https://name-repos.git>` | Add an upstream repo to the local repo. |
| `git branch --set-upstream-to <remote/bname>`  |   Track the upstream main branch wrt keeping sync |

: Common git commands {.striped .hover}

